repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            "feat",
            "fix",
            "doc",
            "perf",
            "refactor",
            "style",
            "test",
            "chore",
            "security",
          ]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
        stages: [prepare-commit-msg]
